on:
  push:
    paths:
      - 'targets/apps/VAmPI-master/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v2
      - name: Run Horusec
        run: |
          ls -R
          #cd ./opensourcetargets/apps/VAmPI-master
          #bash <(curl -s https://raw.githubusercontent.com/0xtiago/opensource-devsecops/main/tools/horusec/horusec.sh)
          shell: bash
